version: '3.8'

services:
  ngrok-like-server:
    image: goshops/k8-tunnel:latest
    ports:
      - "3000:3000"
    volumes:
      - ./data:/usr/src/app/data
    environment:
      - NODE_ENV=production
    restart: unless-stopped

volumes:
  data: